version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build:
    docker:
      - image: cimg/node:20.17
    steps:
      - checkout
      - run: corepack enable
      - run: npm --version
      - run: pnpm --version || npm i -g pnpm@10
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
workflows:
  build_and_test:
    jobs:
      - build
